version: "3.9"
services:
  app:
    image: python:3.12-slim
    container_name: vlmphoto_app_p1
    working_dir: /app
    init: true
    env_file:
      - ./.env.p1.sample
      # copy to .env.p1 and edit for local paths; compose will pick that up if you switch the filename
    volumes:
      - ../backend:/app
      - ./data/originals:/data/originals
      - ./data/derived:/data/derived
    ports:
      - "8000:8000"
    command: >-
      bash -lc "pip install -U pip && pip install -r requirements.txt &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000"
    # For GPUs on Linux with NVIDIA Container Toolkit, uncomment:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
